version: 2

sources:
  - name: IMS_FLATTEN_SOURCE
    schema: IMS_SCHEMA
    database: IMS_DB
    tables:
      - name: SF_IMS

models:
  - name: flattened_incidents
    description: "A data flattening dbt model"
    columns:
      - name: _id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
